# Generated by Django 5.2.4 on 2025-07-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tifinar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
