# Generated by Django 5.2.4 on 2025-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tifinar', '0002_alter_comments_options_alter_comments_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='normalized_title',
            field=models.CharField(default='temp_default_value', max_length=500),
        ),
    ]
