# Generated by Django 5.2.4 on 2025-07-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tifinar', '0003_remove_comments_user_comments_normalized_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'comments'},
        ),
    ]
