-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Oct 08, 2025 at 10:52 PM
-- Server version: 11.8.3-MariaDB-log
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u980306597_tifinar`
--

-- --------------------------------------------------------

--
-- Table structure for table `msgs`
--

CREATE TABLE `msgs` (
  `msg_id` int(11) NOT NULL,
  `Mysubject` mediumtext DEFAULT NULL,
  `Email` text DEFAULT NULL,
  `title` text DEFAULT NULL,
  `Author` varchar(255) DEFAULT NULL,
  `author_id` int(11) UNSIGNED DEFAULT NULL,
  `author_img` longtext DEFAULT NULL,
  `recipient` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `status` enum('read','unread','important') NOT NULL DEFAULT 'unread',
  `dir` enum('rtl','ltr') NOT NULL DEFAULT 'rtl'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `msgs`
--

INSERT INTO `msgs` (`msg_id`, `Mysubject`, `Email`, `title`, `Author`, `author_id`, `author_img`, `recipient`, `created_at`, `updated_at`, `status`, `dir`) VALUES
(18, 'Cc Cv', 'elaceri2008@gmail.com', 'slm', 'آلاء العصري', 10, 'images/users/10/image_alae.webp,images/users/10/oumaima.png,images/users/10/alae.jfif', '1', '2025-01-04 10:00:00', '2025-01-04 10:05:09', 'read', 'rtl'),
(19, 'مرحبا آلاء', 'hbialouan@gmail.com', 'السلام', 'حميد بعلوان', 1, 'images/users/1/حميد_بعلوان_1.webp,\r\nimages/users/1/حميد_بعلوان_2.webp,\r\nimages/users/1/حميد_بعلوان_3.webp,\r\nimages/users/1/حميد_بعلوان_4.jpg,\r\nimages/users/1/حميد_بعلوان_5.jpg,\r\nimages/users/1/حميد_بعلوان_6.jpg,\r\nimages/users/1/حميد_بعلوان_7.jpg,\r\nimages/users/1/حميد_بعلوان_8.jpg,\r\nimages/users/1/حميد_بعلوان_9.jpg,\r\nimages/users/1/حميد_بعلوان_10.jpg,\r\nimages/users/1/حميد_بعلوان_11.jpg,\r\nimages/users/1/حميد_بعلوان_12.jpg,\r\nimages/users/1/حميد_بعلوان_13.jpg,\r\nimages/users/1/حميد_بعلوان_14.jpg,\r\nimages/users/1/حميد_بعلوان_15.jpg,\r\nimages/users/1/حميد_بعلوان_16.jpg,\r\nimages/users/1/حميد_بعلوان_17.jpg', '10', '2025-01-04 10:02:56', '2025-01-04 10:03:25', 'read', 'rtl'),
(20, 'jawbni 🐱‍👤', 'elaceri2008@gmail.com', 'Alo', 'آلاء العصري', 10, 'images/users/10/image_alae.webp,images/users/10/oumaima.png,images/users/10/alae.jfif', '1', '2025-01-04 10:11:37', '2025-01-04 10:11:55', 'read', 'rtl'),
(24, '9blini  3afaq', 'elaceri2008@gmail.com', 'slm', 'آلاء العصري', 10, 'images/users/10/image_alae.webp,images/users/10/oumaima.png,images/users/10/alae.jfif', '6', '2025-01-04 15:08:26', '2025-01-04 15:21:45', 'read', 'rtl'),
(34, 'مرحبا يا خالي حميد هاد الموقع ديال tifinar.net', 'douae@2016', 'مرحبا حميد❤❤🤣😂😍😒😘😍😍', 'douae elaceri', 11, 'images/users/11/242138917457869975.jfif', '1', '2025-01-14 18:37:31', '2025-01-19 19:21:51', 'read', 'rtl'),
(35, 'cv ana alae bikhir😘😍💕💞💞', 'elaceri2008@gmail.com', 'slm sirine', 'آلاء العصري', 10, 'images/users/10/image_alae.webp,images/users/10/oumaima.png,images/users/10/alae.jfif', '12', '2025-01-14 21:34:10', '2025-01-14 21:40:40', 'read', 'rtl'),
(36, 'سلام', 'sirinebellihi@gmail.com', NULL, 'sirine bellihi', 12, 'images/users/12/sirine.jpeg', '10', '2025-01-14 21:40:49', '2025-01-18 14:12:26', 'read', 'rtl'),
(37, 'ههه', 'sirinebellihi@gmail.com', NULL, 'sirine bellihi', 12, 'images/users/12/sirine.jpeg', '10', '2025-01-14 21:41:07', '2025-01-18 14:13:44', 'read', 'rtl'),
(39, 'نعم، إنه موقع tifinar.net .. أجمل موقع في العالم 🔆', 'hbialouan@gmail.com', 'أهلا دعاء 😄😊', 'حميد بعلوان', 1, 'images/users/1/حميد_بعلوان_1.webp,\r\nimages/users/1/حميد_بعلوان_2.webp,\r\nimages/users/1/حميد_بعلوان_3.webp,\r\nimages/users/1/حميد_بعلوان_4.jpg,\r\nimages/users/1/حميد_بعلوان_5.jpg,\r\nimages/users/1/حميد_بعلوان_6.jpg,\r\nimages/users/1/حميد_بعلوان_7.jpg,\r\nimages/users/1/حميد_بعلوان_8.jpg,\r\nimages/users/1/حميد_بعلوان_9.jpg,\r\nimages/users/1/حميد_بعلوان_10.jpg,\r\nimages/users/1/حميد_بعلوان_11.jpg,\r\nimages/users/1/حميد_بعلوان_12.jpg,\r\nimages/users/1/حميد_بعلوان_13.jpg,\r\nimages/users/1/حميد_بعلوان_14.jpg,\r\nimages/users/1/حميد_بعلوان_15.jpg,\r\nimages/users/1/حميد_بعلوان_16.jpg,\r\nimages/users/1/حميد_بعلوان_17.jpg', '11', '2025-01-16 19:20:15', '2025-02-02 16:49:07', 'unread', 'rtl'),
(40, 'ha ana jawbtek', 'hbialouan@gmail.com', 'bonjour alae', 'حميد بعلوان', 1, 'images/users/1/حميد_بعلوان_1.webp,\r\nimages/users/1/حميد_بعلوان_2.webp,\r\nimages/users/1/حميد_بعلوان_3.webp,\r\nimages/users/1/حميد_بعلوان_4.jpg,\r\nimages/users/1/حميد_بعلوان_5.jpg,\r\nimages/users/1/حميد_بعلوان_6.jpg,\r\nimages/users/1/حميد_بعلوان_7.jpg,\r\nimages/users/1/حميد_بعلوان_8.jpg,\r\nimages/users/1/حميد_بعلوان_9.jpg,\r\nimages/users/1/حميد_بعلوان_10.jpg,\r\nimages/users/1/حميد_بعلوان_11.jpg,\r\nimages/users/1/حميد_بعلوان_12.jpg,\r\nimages/users/1/حميد_بعلوان_13.jpg,\r\nimages/users/1/حميد_بعلوان_14.jpg,\r\nimages/users/1/حميد_بعلوان_15.jpg,\r\nimages/users/1/حميد_بعلوان_16.jpg,\r\nimages/users/1/حميد_بعلوان_17.jpg', '10', '2025-01-16 19:24:36', '2025-01-24 16:38:41', 'read', 'rtl'),
(45, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '13', '2025-01-20 00:29:25', '2025-02-02 16:50:02', 'unread', 'rtl'),
(46, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', NULL, 'images/users/14/tifinar.webp', '5', '2025-01-20 00:39:17', '2025-06-18 22:11:47', 'read', 'rtl'),
(47, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '6', '2025-01-20 00:41:56', '2025-02-02 16:55:09', 'read', 'rtl'),
(48, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '7', '2025-01-20 00:42:16', '2025-02-02 16:33:57', 'unread', 'rtl'),
(49, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '8', '2025-01-20 00:42:48', '2025-02-02 16:50:28', 'unread', 'rtl'),
(50, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '9', '2025-01-20 00:42:48', '2025-02-02 16:33:48', 'unread', 'rtl'),
(51, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '10', '2025-01-20 00:42:48', '2025-02-09 15:07:19', 'read', 'rtl'),
(52, '<style>\n        body {\n            background-color: #f8f9fa;\n            font-family: \'Arial\', sans-serif;\n        }\n        .card {\n            margin: 20px auto;\n            max-width: 600px;\n            border: 2px solid #007bff;\n            border-radius: 10px;\n            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n        }\n        .card-header {\n            background-color: #007bff;\n            color: white;\n            font-size: 1.5rem;\n            text-align: center;\n            font-weight: bold;\n        }\n        .card-body {\n            text-align: center;\n            padding: 20px;\n        }\n        .btn-primary {\n            background-color: #007bff;\n            border: none;\n        }\n        .btn-primary:hover {\n            background-color: #0056b3;\n        }\n    </style>\n<div class=\"card\">\n    <div class=\"card-header\">\n        💡 مسابقة \"أفضل اقتراح\" 💡\n    </div>\n    <div class=\"card-body\">\n        <p class=\"card-text\">نحب دائمًا سماع أفكاركم الإبداعية! 🤩 شاركنا اقتراحك لتحسين موقعنا، وأفضل اقتراح سيحصل على <strong>جائزة رائعة</strong>! 🎁</p>\n        <p>لا تفوت الفرصة :</p>\n        <a href=\"https://tifinar.net/%D8%A7%D8%AA%D8%B5%D9%84_%D8%A8%D9%86%D8%A7?user_id=14\" class=\"btn btn-primary\">أرسل اقتراحك الآن</a>\n    </div>\n    <div class=\"card-footer text-center text-muted\">\n        ⏳ المسابقة مستمرة حتى نهاية الشهر. سارع بالمشاركة!\n    </div>\n</div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '11', '2025-01-20 00:42:48', '2025-02-02 16:34:19', 'unread', 'rtl'),
(53, '<style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f8f9fa;\n            text-align: center;\n            padding: 20px;\n            direction: rtl;\n        }\n        .game-container {\n            background: #ffffff;\n            padding: 20px;\n            border-radius: 12px;\n            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n            display: inline-block;\n            max-width: 500px;\n        }\n        h2 {\n            color: #007bff;\n        }\n        p {\n            color: #333;\n            font-size: 18px;\n            line-height: 1.6;\n        }\n        .game-link {\n            display: inline-block;\n            background: #28a745;\n            color: #fff;\n            padding: 10px 20px;\n            font-size: 20px;\n            text-decoration: none;\n            border-radius: 8px;\n            margin-top: 10px;\n            transition: 0.3s;\n        }\n        .game-link:hover {\n            background: #218838;\n            transform: scale(1.05);\n        }\n        .icon {\n            font-size: 50px;\n            color: #ff9800;\n        }\n    </style>  <div class=\"game-container\">\n        <i class=\"fas fa-gamepad icon\"></i>\n        <h2>🎮 مرحبًا بكم في عالم تيفيناغ!</h2>\n        <p>\n            موقع <strong>تيفيناغ</strong> لم يعد مجرد منصة للدراسة والتثقيف،  \n            بل أصبح نافذة رائعة للعب والاستمتاع! 🎉<br>  \n            استعدوا لاكتشاف ألعاب جديدة ومسلية يمكنكم تجربتها من وقت لآخر.  \n        </p>\n        <p>إليكم لعبة <strong>حجرة - ورقة - مقص</strong> الرائعة:</p>\n        <a href=\"https://tifinar.net/game\" class=\"game-link\">🚀 إلعب الآن</a>\n    </div>', 'contact@tifinar.net', 'أصبح بإمكانكم اللعب في موقع tifinar.net', 'موقع تيفيناغ', 14, 'images/users/14/tifinar.webp', '12', '2025-01-20 00:42:48', '2025-03-17 15:05:53', 'read', 'rtl');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `msgs`
--
ALTER TABLE `msgs`
  ADD PRIMARY KEY (`msg_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `msgs`
--
ALTER TABLE `msgs`
  MODIFY `msg_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
