-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 14, 2025 at 04:39 PM
-- Server version: 11.8.2-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tifinar`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `books_id` int(11) NOT NULL,
  `Myimage` varchar(500) DEFAULT NULL,
  `title` tinytext DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `Mysubject` mediumtext DEFAULT NULL,
  `Mydescription` text DEFAULT NULL,
  `keywords` longtext DEFAULT NULL,
  `Author` tinytext DEFAULT NULL,
  `autre` varchar(255) DEFAULT NULL,
  `the_type` varchar(255) DEFAULT NULL,
  `dir` enum('rtl','ltr') DEFAULT 'ltr',
  `language` varchar(255) DEFAULT NULL,
  `visibility_status` enum('public','under_review','restricted') NOT NULL DEFAULT 'under_review',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `gender` enum('male','female','all') NOT NULL DEFAULT 'all',
  `min_age` tinyint(4) NOT NULL DEFAULT 2,
  `max_age` tinyint(4) NOT NULL DEFAULT 75,
  `educational_level` enum('0','1','2','3','4','5','6','7','8','9','10','11','12','13') NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`books_id`, `Myimage`, `title`, `slug`, `Mysubject`, `Mydescription`, `keywords`, `Author`, `autre`, `the_type`, `dir`, `language`, `visibility_status`, `updated_at`, `created_at`, `gender`, `min_age`, `max_age`, `educational_level`) VALUES
(2, 'tamusni_turari.webp', 'ⵜⴰⵎⵓⵙⵏⵉ ⵜⵓⵔⴰⵔⵉ - مجلة أمازيغية للأطفال', 'ⵜⴰⵎⵓⵙⵏⵉ_ⵜⵓⵔⴰⵔⵉ_مجلة_أمازيغية_للأطفال', '<p>    ⵜⴰⵎⵓⵙⵏⵉ ⵜⵓⵔⴰⵔⵉ : هي مجلة للصغار  تهدف لتشجيع الأطفال على تعلم الأمازيغية بأحرف تيفيناغ ، حيث تضم ألعاب ممتعة تعتمد على أحرف تيفيناغ سهلة وصور توضيحية جميلة، سيحب الأطفال هده المجلة بالتأكيد لأنها صممت خصيصا لأجلهم ولأجل تنمية معارفهم ودكائهم .</p>				', 'ⵜⴰⵎⵓⵙⵏⵉ ⵜⵓⵔⴰⵔⵉ هي مجلة للصغار  تهدف لتشجيع الأطفال على تعلم الأمازيغية بأحرف تيفيناغ ، حيث تضم ألعاب ممتعة تعتمد على أحرف تيفيناغ سهلة وصور توضيحية جميلة، سيحب الأطفال هده المجلة بالتأكيد لأنها صممت خصيصا لأجلهم ولأجل تنمية معارفهم ودكائهم.', 'مجلة أمازيغية,tamusni turari,ⵜⴰⵎⵓⵙⵏⵉ ⵜⵓⵔⴰⵔⵉ,مجلة للأطفال,مكتبة تيفيناغ', 'حميد بعلوان', 'tamusni_turari.pdf', 'مجلات, الأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:08:14', '2024-09-09 23:00:00', 'all', 2, 75, '0'),
(3, 'tifinagh.webp', 'تيفيناغ في أربع خطوات', 'تيفيناغ_في_أربع_خطوات', '    <p> هدا الكتاب هو محاولة لتبسيط اللغة الأمازيغية لمن بدأوا للتوفي تعلمها من الصفر، ويضم بين طياته صور توضيحية للمساعدة على الفهم وكدا للاستئاس، كما استعمل المؤلف أيضا أدوات عدة وألوان مختلفة للمساعدة وتسهيل القراءة على من ليست لديهم أية خلفية معرفية في اللغة الأمازيغية.\r\n</p>\r\n<i>نتمنى لكم قراءة ممتعة</i>', ' هدا الكتاب هو محاولة لتبسيط اللغة الأمازيغية لمن بدأوا للتوفي تعلمها من الصفر، ويضم بين طياته صور توضيحية للمساعدة على الفهم وكدا للاستئاس، كما استعمل المؤلف أيضا أدوات عدة وألوان مختلفة للمساعدة وتسهيل القراءة على من ليست لديهم أية خلفية معرفية في اللغة الأمازيغية', ' هدا الكتاب هو محاولة لتبسيط اللغة الأمازيغية لمن بدأوا للتوفي تعلمها من الصفر، ويضم بين طياته صور توضيحية للمساعدة على الفهم وكدا للاستئاس، كما استعمل المؤلف أيضا أدوات عدة وألوان مختلفة للمساعدة وتسهيل القراءة على من ليست لديهم أية خلفية معرفية في اللغة الأمازيغية', 'حميد بعلوان', 'تيفيناغ_في_أربع_خطوات.pdf', 'الأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '1'),
(4, 'agldun.webp', 'ⴰⴳⵍⴷⵓⵏ ⴰⵎⵥⵥⴰⵏ', 'ⴰⴳⵍⴷⵓⵏ_ⴰⵎⵥⵥⴰⵏ', '<p>    هنا يمكنك تحميل قصة : ⴰⴳⵍⴷⵓⵏ ⴰⵎⵥⵥⴰⵏ .\r\n                                  </p>\r\n                        نتمنى لكم قراءة ممتعة. ', 'هنا يمكنك تحميل قصة : ⴰⴳⵍⴷⵓⵏ ⴰⵎⵥⵥⴰⵏ \r\nنتمنى لكم قراءة ممتعة.                                                                                    ', 'هنا يمكنك تحميل قصة : ⴰⴳⵍⴷⵓⵏ ⴰⵎⵥⵥⴰⵏ                                                      ', '', 'agldun.pdf', 'قصص و روايات, الأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(5, 'augustin.webp', 'الاعترافات - القديس أوغسطين', 'الاعترافات_القديس_أوغسطين', 'الاعترافات أو اعترافاتي هو مجموعة من مؤلفات القديس أوغسطين يحكي فيها عن حياته ويبين فيها كيف تعرف على الله ليتبنى بعد دلك للفكر المسيحي.', 'الاعترافات أو اعترافاتي هو مجموعة من مؤلفات القديس أوغسطين يحكي فيها عن حياته ويبين فيها كيف تعرف على الله ليتبنى بعد دلك للفكر المسيحي.', 'الاعترافات أو اعترافاتي هو مجموعة من مؤلفات القديس أوغسطين يحكي فيها عن حياته ويبين فيها كيف تعرف على الله ليتبنى بعد دلك للفكر المسيحي.', '', 'i3tirafat.pdf', 'قصص و روايات', 'rtl', 'amz', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 15, 75, '10'),
(8, 'sidi_hamou_talb.webp', 'الشعر الأمازيغي المنسوب - لسيدي حمو طالب', 'الشعر_الأمازيغي_المنسوب_لسيدي_حمو_طالب', '<p>    في هدا المؤلف ستجدون مجموعة من القصائد الشعرية الأمازيغية المنسوبة للشاعر المعروف بسيدي حمو طالب، والتي لا يزال العديد من سكان منطقة سوس يتغنون بها. </p>', '  في هدا المؤلف ستجدون مجموعة من القصائد الشعرية الأمازيغية المنسوبة للشاعر المعروف بسيدي حمو طالب، والتي لا يزال العديد من سكان منطقة سوس يتغنون بها ', '  في هدا المؤلف ستجدون مجموعة من القصائد الشعرية الأمازيغية المنسوبة للشاعر المعروف بسيدي حمو طالب، والتي لا يزال العديد من سكان منطقة سوس يتغنون بها ', '', 'sidi-hamou-talb.pdf', 'قصائد شعرية, الأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:11:17', '2024-09-09 23:00:00', 'all', 14, 75, '3'),
(9, 'tamusni_2.webp', 'مجلة المعرفة الجزء 2 - ⵜⴰⵎⵓⵙⵏⵉ', 'مجلة_المعرفة_الجزء_2_ⵜⴰⵎⵓⵙⵏⵉ', '<p>    مجلة المعرفة تصدر من ليبيا وتهدف لتعليم الأمازيغية للأطفال وتشجيعهم على قراءتها. </p>                                 ', 'مجلة المعرفة تصدر من ليبيا وتهدف لتعليم الأمازيغية للأطفال وتشجيعهم على قراءتها                                  ', 'مجلة المعرفة تصدر من ليبيا وتهدف لتعليم الأمازيغية للأطفال وتشجيعهم على قراءتها                                  ', '', 'tamusni_2.pdf', 'مجلات, الأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:08:14', '2024-09-09 23:00:00', 'all', 2, 75, '0'),
(10, 'tizlatin.webp', 'ⵜⵉⵣⵍⴰⵜⵉⵏ ⵉⵏⵓ', 'ⵜⵉⵣⵍⴰⵜⵉⵏ_ⵉⵏⵓ', '<p>    ⵜⵉⵣⵍⴰⵜⵉⵏ ⵉⵏⵓ أو قصائدي، هي مجموعة من الأناشيد الجميلة للأطفال باللغة الأمازيغية، من شأنها تطوير رصيدهم اللغوي وتشجيعهم على المطالعة بالأمازيغية. </p>                                           ', 'ⵜⵉⵣⵍⴰⵜⵉⵏ ⵉⵏⵓ أو قصائدي، هي مجموعة من الأناشيد الجميلة للأطفال باللغة الأمازيغية، من شأنها تطوير رصيدهم اللغوي وتشجيعهم على المطالعة بالأمازيغية.', 'ⵜⵉⵣⵍⴰⵜⵉⵏ ⵉⵏⵓ أو قصائدي، هي مجموعة من الأناشيد الجميلة للأطفال باللغة الأمازيغية، من شأنها تطوير رصيدهم اللغوي وتشجيعهم على المطالعة بالأمازيغية.', '', 'tizlatin.pdf', 'قصائد شعرية, الأمازيغيةالأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'female', 2, 75, '0'),
(33, 'tirah.webp', 'ⵜⵉⵔⴰ - كتاب لتعلم الكتابة بأحرف تيفيناغ', 'ⵜⵉⵔⴰ_كتاب_لتعلم_الكتابة_بأحرف_تيفيناغ', 'كتاب ⵜⵉⵔⴰ يهدف لتعليم الكتابة بأحرف تيفيناغ، ينصح بتحميله بصيغة pdf ثم طباعته على الورق لمن يرغب في تحسين خط أثناء الكتابة بالأحرف الأمازيغية تيفيناغ.							', 'كتاب ⵜⵉⵔⴰ يهدف لتعليم الكتابة بأحرف تيفيناغ، ينصح بتحميله بصيغة pdf ثم طباعته على الورق لمن يرغب في تحسين خط أثناء الكتابة بالأحرف الأمازيغية تيفيناغ.						', 'كتاب ⵜⵉⵔⴰ يهدف لتعليم الكتابة بأحرف تيفيناغ، ينصح بتحميله بصيغة pdf ثم طباعته على الورق لمن يرغب في تحسين خط أثناء الكتابة بالأحرف الأمازيغية تيفيناغ.						', 'حميد بعلوان', 'tira.pdf', 'الأمازيغية', 'rtl', 'amz', 'public', '2025-09-08 23:08:14', '2024-09-09 23:00:00', 'all', 5, 75, '0'),
(34, 'francais1.webp', 'Le français en images', 'Le_français_en_images', 'Vocabulaire : Une centaine de mots imagés pour trouver facilement celui que tu cherches. • Grammaire: Les règles de base du français. ', 'Vocabulaire : Une centaine de mots imagés pour trouver facilement celui que tu cherches. • Grammaire: Les règles de base du français. ', 'Vocabulaire : Une centaine de mots imagés pour trouver facilement celui que tu cherches. • Grammaire: Les règles de base du français. ', '', 'Le français en images.pdf', 'Apprendre le français, القواميس اللغوية - Dictionaries', 'ltr', 'Fr', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(35, 'francais2.webp', 'Dictionnaire illustre', 'Dictionnaire_illustre', 'Mon premier dictionnaire francais en images. Mon premier dictionnaire anglais-français. Mon Premier Dictionnaire Bilingue Français-anglais.', 'Mon premier dictionnaire francais en images. Mon premier dictionnaire anglais-français. Mon Premier Dictionnaire Bilingue Français-anglais.', 'Mon premier dictionnaire francais en images. Mon premier dictionnaire anglais-français. Mon Premier Dictionnaire Bilingue Français-anglais.', '', 'Fp_FLS_dictionnaire_illustre_eli_junior-4.pdf', 'Apprendre le français, القواميس اللغوية - Dictionaries', 'ltr', 'Fr', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(36, 'English1.webp', 'Dictionnaire visuel bilingue français Anglais', 'Dictionnaire_visuel_bilingue_français_Anglais', 'Une fois que vous serez plus sûr de vous, choisissez des mots dans l\'index de la langue étrangère et essayez de voir si vous en connaissez le sens ', 'Une fois que vous serez plus sûr de vous, choisissez des mots dans l\'index de la langue étrangère et essayez de voir si vous en connaissez le sens ', 'Une fois que vous serez plus sûr de vous, choisissez des mots dans l\'index de la langue étrangère et essayez de voir si vous en connaissez le sens ', '', 'Dictionnaire visuel bilingue français Anglais.pdf', 'Learn English, القواميس اللغوية - Dictionaries, الانجليزية', 'ltr', 'En', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(37, 'francais3.webp', 'Le grand dictionnaire en images', 'Le_grand_dictionnaire_en_images', 'Cette édition numérique a été fabriquée par la société FeniXX au format PDF. La couverture reproduit celle du livre original conservé au sein des collections ', 'Cette édition numérique a été fabriquée par la société FeniXX au format PDF. La couverture reproduit celle du livre original conservé au sein des collections ', 'Cette édition numérique a été fabriquée par la société FeniXX au format PDF. La couverture reproduit celle du livre original conservé au sein des collections ', '', '9782307525912.pdf', 'Apprendre le français, القواميس اللغوية - Dictionaries', 'ltr', 'Fr', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(38, 'SVT1.webp', ' Découverte d’un milieu naturel-Cours-1-Word', 'Découverte_d_un_milieu_naturel_Cours_1_Word', '•	Dans la nature, il existe de nombreux endroits différents :  la foret, les rivières, la mer, la plage, l’étang, le lac…', '•	Dans la nature, il existe de nombreux endroits différents :  la foret, les rivières, la mer, la plage, l’étang, le lac…', '•	Dans la nature, il existe de nombreux endroits différents :  la foret, les rivières, la mer, la plage, l’étang, le lac…', '', 'Decouverte-dun-milieu-naturel-Cours-1-Word.docx', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(39, 'SVT2.webp', 'Découverte d’un milieu naturel-Cours-2-Word', 'Découverte_d_un_milieu_naturel_Cours_2_Word', 'Decouverte dun milieu naturel ', 'Decouverte dun milieu naturel ', 'Decouverte dun milieu naturel ', '', 'Decouverte-dun-milieu-naturel-Cours-2-Word.docx', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(40, 'SVT3.webp', 'Découverte d’un milieu naturel-Cours-3-PDF', 'Découverte_d_un_milieu_naturel_Cours_3_PDF', 'Découverte d\'un milieu naturel Cours-1 ', 'Découverte d\'un milieu naturel Cours-1 ', 'Découverte d\'un milieu naturel Cours-1 ', '', 'Decouverte-dun-milieu-naturel-Cours-1-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(41, 'SVT4.webp', ' Découverte d’un milieu naturel-Cours-4-PDF', 'Découverte_d_un_milieu_naturel_Cours_4_PDF', 'Decouverte-dun-milieu-naturel-Cours-2-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-2-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-2-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-2-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(42, 'SVT5.webp', 'Découverte d’un milieu naturel-Cours-5-PDF', 'Découverte_dun_milieu_naturel_Cours_5_PDF', 'Decouverte-dun-milieu-naturel-Cours-3-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-3-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-3-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-3-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(43, 'SVT6.webp', 'Découverte d’un milieu naturel-Cours-6-PDF', 'Découverte_dun_milieu_naturelCours_6_PDF', 'Decouverte-dun-milieu-naturel-Cours-4-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-4-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-4-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-4-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(44, 'SVT7.webp', ' Découverte d’un milieu naturel-Cours-7-PDF', 'Découverte_dun_milieu_naturel_Cours_7_PDF', 'Decouverte-dun-milieu-naturel-Cours-5-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-5-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-5-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-5-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(45, 'SVT8.webp', 'Découverte d’un milieu naturel-Cours-8-PDF', 'Découverte_dun_milieu_naturel_Cours_8_PDF', 'Decouverte-dun-milieu-naturel-Cours-6-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-6-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-6-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-6-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(46, 'SVT9.webp', 'Découverte d’un milieu naturel-Cours-9-PDF', 'Découverte_dun_milieu_naturel_Cours_9_PDF', 'Decouverte-dun-milieu-naturel-Cours-7-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-7-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-7-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-7-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(47, 'SVT10.webp', 'Découverte d’un milieu naturel-Cours-10-PDF', 'Découverte_dun_milieu_naturel_Cours_10_PDF', 'Decouverte-dun-milieu-naturel-Cours-8-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-8-PDF.pdf', 'Decouverte-dun-milieu-naturel-Cours-8-PDF.pdf', '', 'Decouverte-dun-milieu-naturel-Cours-8-PDF.pdf', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(48, 'SVT11.webp', ' Découverte d’un milieu naturel-Cours-11-PPT', 'Découverte_dun_milieu_naturel_Cours_11_PPT', 'Decouverte-dun-milieu-naturel-Cours-1-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-1-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-1-PPT.pptx', '', 'Decouverte-dun-milieu-naturel-Cours-1-PPT.pptx', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(49, 'SVT12.webp', 'Découverte d’un milieu naturel-Cours-12-PPT', 'Découverte_dun_milieu_naturel_Cours_12_PPT', 'Decouverte-dun-milieu-naturel-Cours-2-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-2-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-2-PPT.pptx', '', 'Decouverte-dun-milieu-naturel-Cours-2-PPT.pptx', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(50, 'SVT13.webp', 'Découverte d’un milieu naturel-Cours-13-PPT', 'Découverte_dun_milieu_naturel_Cours_13_PPT', 'Decouverte-dun-milieu-naturel-Cours-6-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-6-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-6-PPT.pptx', '', 'Decouverte-dun-milieu-naturel-Cours-6-PPT.pptx', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(51, 'SVT14.webp', ' Découverte d’un milieu naturel-Cours-14-PPT', 'Découverte_d_un_milieu_naturel_Cours_14_PPT', 'Decouverte-dun-milieu-naturel-Cours-4-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-4-PPT.pptx', 'Decouverte-dun-milieu-naturel-Cours-4-PPT.pptx', '', 'Decouverte-dun-milieu-naturel-Cours-4-PPT.pptx', 'SVT,علوم الحياة والأرض', 'ltr', 'Fr', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(52, 'Physique_chimie1.webp', ' Les états physiques de la matière-Word-1', 'Les_états_physiques_de_la_matière_Word_1', ' Les états physiques de la matière-Word-1', ' Les états physiques de la matière-Word-1 ', ' Les états physiques de la matière-Word-1', '', '01-Les-etats-physiques-de-la-matiere-1.docx', 'الفزياء والكيمياء', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(53, 'Physique_chimie2.webp', '02-Les-etats-physiques-de-la-matiere-1.docx', '02_Les_etatsphysiques_de_la_matiere_1_docx', '02-Les-etats-physiques-de-la-matiere-1.docx', '02-Les-etats-physiques-de-la-matiere-1.docx', '02-Les-etats-physiques-de-la-matiere-1.docx', '', '02-Les-etats-physiques-de-la-matiere-1.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(54, 'Physique_chimie3.webp', 'Les états physiques de la matière-Word-3', 'Les_états_physiques_de_la_matière_Word_3', 'Les états physiques de la matière-Word-3', 'Les états physiques de la matière-Word-3', 'Les états physiques de la matière-Word-3', '', '03-Les-etats-physiques-de-la-matiere.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(55, 'Physique_chimie4.webp', ' Les états physiques de la matière-Word-4', 'Les_états_physiques_de_la_matière_Word_4', '04-Les-etats-physiques-de-la-matiere-1.docx', '04-Les-etats-physiques-de-la-matiere-1.docx', '04-Les-etats-physiques-de-la-matiere-1.docx', '', '04-Les-etats-physiques-de-la-matiere-1.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(56, 'Physique_chimie5.webp', 'Les états physiques de la matière-Word-5', 'Les_états_physiques_de_la_matière_Word_5', 'Les états physiques de la matière-Word-5', 'Les états physiques de la matière-Word-5', 'Les états physiques de la matière-Word-5', '', '05-Les-etats-physiques-de-la-matiere-1.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(57, 'Physique_chimie6.webp', 'Les états physiques de la matière-Word-6', 'Les_états_physiques_de_la_matière_Word_6', 'Les états physiques de la matière-Word-6', 'Les états physiques de la matière-Word-6', 'Les états physiques de la matière-Word-6', '', 'cours-4-LES-ETATS-PHYSIQUES-DE-LA-MATIERE.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(58, 'Physique_chimie7.webp', '• Les états physiques de la matière-Word-7', 'Les_états_physiques_de_la_matière_Word_7', '• Les états physiques de la matière-Word-7\r\n', '• Les états physiques de la matière-Word-7\r\n', '• Les états physiques de la matière-Word-7\r\n', '', 'cours-5-LES-ETATS-PHYSIQUES-DE-LA-MATIERE.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(59, 'Physique_chimie8.webp', '• Les états physiques de la matière-Word-8', 'Les_états_physiques_de_la_matière_Word_8', '• Les états physiques de la matière-Word-8\r\n', '• Les états physiques de la matière-Word-8\r\n', '• Les états physiques de la matière-Word-8\r\n', '', 'cours-6-LES-ETATS-PHYSIQUES-DE-LA-MATIERE.docx', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(60, 'Physique_chimie9.webp', '• Les états physiques de la matière-', 'Les_états_physiques_de_la_matière', '• Les états physiques de la matière-PDF-9\r\n', '• Les états physiques de la matière-PDF-9\r\n', '• Les états physiques de la matière-PDF-9\r\n', '', 'cours-4-LES-ETATS-PHYSIQUES-DE-LA-MATIERE', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(61, 'Physique_chimie10.webp', '• Les états physiques de la matière-PPT-10', 'Les_états_physiques_de_la_matière_PPT_10', '• Les états physiques de la matière-PPT-10\r\n', '• Les états physiques de la matière-PPT-10\r\n', '• Les états physiques de la matière-PPT-10\r\n', '', 'les-etats-physiques-de-la-matiere-cours-ppt-1.pdf', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(62, 'Physique_chimie11.webp', '• Les états physiques de la matière-PPT-11', 'Les_états_physiques_de_la_matière_PPT_11', '• Les états physiques de la matière-', '• Les états physiques de la matière-', '• Les états physiques de la matière-', '', 'les-etats-physiques-de-la-matiere-cours-ppt-1.pdf', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(63, 'Physique_chimie12.webp', '• Les états physiques de la matière-PPT-12', 'Les_états_physiques_de_la_matière_PPT_12', '• Les états physiques de la matière-PPT-12\r\n', '• Les états physiques de la matière-PPT-12\r\n', '• Les états physiques de la matière-PPT-12\r\n', '', 'les-etats-physiques-de-la-matiere-cours-ppt-3-2.pdf', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(64, 'Physique_chimie13.webp', '• Les états physiques de la matière _ 13', 'Les_états_physiques_de_la_matière_PPT_13', '• Les états physiques de la matière-PPT-13\r\n', '• Les états physiques de la matière-PPT-13\r\n', '• Les états physiques de la matière-PPT-13\r\n', '', 'les-etats-physiques-de-la-matiere-cours-ppt-4.pdf', 'الفزياء , physique, physic', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(65, 'math1.webp', '• Évaluation diagnostique', 'Évaluation_diagnostique', '• Évaluation diagnostique-Maths-1AC-Modèle-1-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-1-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-1-Word\r\n', '', 'TEST-DIAGNOSTIQUE-Maths-1ac.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(66, 'math2.webp', '• Évaluation diagnostique Modèle 2', 'Évaluation_diagnostique_Modèle_2_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-2-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-2-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-2-Word\r\n', '', 'الرائز-التشخيصي-لتقويم-المستلزمات-الدراسية.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(67, 'math3.webp', '• Évaluation diagnostique Modèle 3', 'Évaluation_diagnostique_Modèle_3_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-3-PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-3-PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-3-PDF', '', 'الرائز-التشخيصي-لتقويم-المستلزمات-الدراسية.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(68, 'math4.webp', '• Évaluation diagnostique Modèle 4', 'Évaluation_diagnostique_Modèle_4_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-4-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-4-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-4-PDF\r\n', '', 'الرائز-التشخيصي-لتقويم-المستلزمات-الدراسية.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(69, 'math5.webp', '• Évaluation diagnostique Modèle 5', 'Évaluation_diagnostique_Modèle_5_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-5-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-5-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-5-Word\r\n', '', 'تقويم-تشخيصي-لمادة-الرياضيات-السنة-الاولى-اعدادي.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(70, 'math6.webp', '• Évaluation diagnostique Modèle 6', 'Évaluation_diagnostique_Modèle_6_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-6-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-6-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-6-PDF\r\n', '', 'eval-diagnostiq-college_1_.pdf', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(71, 'math7.webp', '• Évaluation diagnostique Modèle 7', 'Évaluation_diagnostique_Modèle_7_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-7-PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-7-PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-7-PDF', '', 'eval-diagnostiq-college_2_.pdf', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 9, 75, '4'),
(72, 'math8.webp', '• Évaluation diagnostique Modèle 8', 'Évaluation_diagnostique_Modèle_8_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-8-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-8-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-8-PDF\r\n', '', '1AC-francais-teste-1-diagnostique.pdf', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(73, 'math9.webp', '• Évaluation diagnostique Modèle 9 ', 'Évaluation_diagnostique_Modèle_9_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-9-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-9-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-9-Word\r\n', '', '1ac-test-diag.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(74, 'math10.webp', '• Évaluation diagnostique Modèle 10', 'Évaluation_diagnostique_Modèle_10_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-10-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-10-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-10-Word\r\n', '', '1ac-test-diag.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(75, 'math11.webp', '• Évaluation diagnostique Modèle-11-Word', 'Évaluation_diagnostique_Modèle_11_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-11-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-11-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-11-Word\r\n', '', '1ac-test-d.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(76, 'math12.webp', '• Évaluation diagnostique-Modèle-12-Word', 'Évaluation_diagnostique_Modèle_12_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-12-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-12-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-12-Word\r\nالرياضيات', '', '1ac-test-dia.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(77, 'math13.webp', '• Évaluation diagnostique-Maths-1AC-Modèle-13-Word', 'Évaluation_diagnostique_Modèle_13_Word', '• Évaluation diagnostique-Maths-1AC-Modèle-13-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-13-Word\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-13-Word\r\n', '', 'teste-diagnostique-1AC-2020-2021-2.docx', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(78, 'math14.webp', '• Évaluation diagnostique Modèle 14 PDF', 'Évaluation_diagnostique_Modèle_14_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-14-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-14-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-14-PDF\r\nالرياضيات', '', '1AC-francais-teste-2-diagnostique.pdf', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(79, 'math15.webp', '• Évaluation diagnostique-Maths-1AC-Modèle-15-PDF', 'Évaluation_diagnostique_Modèle_15_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-15-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-15-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-15-PDF\r\n', '', '1AC-Francais-Controles-diagnostique.pdf', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(80, 'math16.webp', '• Évaluation diagnostique-Modèle-16-PDF', 'Évaluation_diagnostique_Modèle_16_PDF', '• Évaluation diagnostique-Maths-1AC-Modèle-16-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-16-PDF\r\n', '• Évaluation diagnostique-Maths-1AC-Modèle-16-PDF\r\n', '', 'teste-diagnostique-1AC-2020-2021-2.pdf', 'maths, رياضيات,mathimaticss,mathimatique', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(81, 'informatique1.webp', 'Information – Informatique', 'Information_Informatique', 'Information – Informatique\r\n', 'Information – Informatique\r\n', 'Information – Informatique\r\n', '', 'nformation-informatique.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '8'),
(82, 'informatique2.webp', 'Système informatique', 'Système_informatique', 'Système informatique', 'Système informatique', 'Système informatique', '', 'systeme-informatique.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '8'),
(83, 'informatique3.webp', 'L’ordinateur et ses constituants', 'Lordinateur_et_ses_constituants', 'L’ordinateur et ses constituants', 'L’ordinateur et ses constituants', 'L’ordinateur et ses constituants', '', 'ordinateur-et-ses-constituants.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(84, 'informatique4.webp', ' Les principaux périphériques d’un ordinateur', 'Les_principaux_périphériques_dun_ordinateur', '\r\nLes principaux périphériques d’un ordinateur\r\n', '\r\nLes principaux périphériques d’un ordinateur\r\n', '\r\nLes principaux périphériques d’un ordinateur\r\n', '', 'les-principaux-peripheriques-d-un-ordinateur.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(85, 'informatique5.webp', 'Connectivité', 'Connectivité', 'Connectivité\r\n', 'Connectivité\r\n', 'Connectivité\r\n', '', 'connectivite.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '8'),
(86, 'informatique6.webp', 'Les logiciels', 'Les_logiciels', 'Les logiciels', 'Les logiciels', 'Les logiciels', '', 'logiciels.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(87, 'informatique7.webp', 'Notion de système d’exploitation', 'Notion_de_système_dexploitation', 'Un système d’exploitation est un logiciel de base capable de contrôler les composants matériels de\r\nl’ordinateur et des autres logiciels, c’est le premier logiciel exécuté lorsqu’on allume l’ordinateur.\r\n', 'Un système d’exploitation est un logiciel de base capable de contrôler les composants matériels de\r\nl’ordinateur et des autres logiciels, c’est le premier logiciel exécuté lorsqu’on allume l’ordinateur.\r\n', 'Un système d’exploitation est un logiciel de base capable de contrôler les composants matériels de\r\nl’ordinateur et des autres logiciels, c’est le premier logiciel exécuté lorsqu’on allume l’ordinateur.', '', 'notions-de-systeme-d-exploitation.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '8'),
(88, 'informatique8.webp', 'Gestion des fenêtres', 'Gestion_des_fenêtres', 'Les fenêtres sont des zones encadrées dans lesquelles on peut trouver le contenu d’un dossier,\r\nd’un fichier ou l’interface d’un programme.', 'Les fenêtres sont des zones encadrées dans lesquelles on peut trouver le contenu d’un dossier,\r\nd’un fichier ou l’interface d’un programme.', 'Les fenêtres sont des zones encadrées dans lesquelles on peut trouver le contenu d’un dossier,\r\nd’un fichier ou l’interface d’un programme.', '', 'gestion-des-fenetres.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(89, 'informatique9.webp', 'Unité II - produire un document multimédia', 'Unité_II_produire_un_document_multimédia', 'Les utilitaires : ce sont des logiciels qui aident à exploiter un ordinateur.\r\nCertains utilitaires font partie du système d’exploitation', 'Les utilitaires : ce sont des logiciels qui aident à exploiter un ordinateur.\r\nCertains utilitaires font partie du système d’exploitation', 'Les utilitaires : ce sont des logiciels qui aident à exploiter un ordinateur.\r\nCertains utilitaires font partie du système d’exploitation', '', 'creation-d-un-fichier-de-dessin-creation-d-un-fichier-son.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-09-09 23:00:00', 'all', 10, 75, '4'),
(90, 'informatique10.webp', 'Gestion d’un document de traitement de texte', 'Gestion_dun_document_de_traitement_de_texte', 'Un traitement de texte ou un texteur est une gamme de logiciels qui permettent de traiterun texte c\'est-à-dire de l’écrire à l’aide du clavier, le mettre en forme, le stocker ou l’enregistrer et de l’imprimer.', 'Un traitement de texte ou un texteur est une gamme de logiciels qui permettent de traiterun texte c\'est-à-dire de l’écrire à l’aide du clavier, le mettre en forme, le stocker ou l’enregistrer et de l’imprimer.\r\n', 'Un traitement de texte ou un texteur est une gamme de logiciels qui permettent de traiterun texte c\'est-à-dire de l’écrire à l’aide du clavier, le mettre en forme, le stocker ou l’enregistrer et de l’imprimer.', '', 'gestion-d-un-document-de-traitement-de-texte.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(91, 'informatique11.webp', 'Gestion d’un document de traitement de texte Saisie d’un texte – Outils de correction linguistique', 'Gestion_dun_document_de_traitement_de_texte_Saisie_dun_texte__Outils_de_correction_linguistique', 'Saisir un texte est le fait de le taper sur ordinateur à l’aide du clavier pour● obtenir un texte numérisé.\r\n● Pour saisir un texte il faut utiliser le logiciel de traitement de texte, Microsoft Word', 'Saisir un texte est le fait de le taper sur ordinateur à l’aide du clavier pour obtenir un texte numérisé.\r\n Pour saisir un texte il faut utiliser le logiciel de traitement de texte, Microsoft Word', 'Saisir un texte est le fait de le taper sur ordinateur à l’aide du clavier pour obtenir un texte numérisé.\r\n Pour saisir un texte il faut utiliser le logiciel de traitement de texte, Microsoft Word', '', 'saisie-d-un-texte-outils-de-correction-linguistique.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(92, 'informatique12.webp', 'Mise en forme – mise en page et impression', 'Mise_en_forme__mise_en_page_et_impression', '● La mise en forme d’un texte est le fait de changer sa forme pour lui donner une bonne présentation.\r\n● La mise en forme des caractères et des mots est le fait de changer leur taille, leur couleur et leur aspect.', ' La mise en forme d’un texte est le fait de changer sa forme pour lui donner une bonne présentation.\r\n La mise en forme des caractères et des mots est le fait de changer leur taille, leur couleur et leur aspect.', ' La mise en forme d’un texte est le fait de changer sa forme pour lui donner une bonne présentation.\r\n La mise en forme des caractères et des mots est le fait de changer leur taille, leur couleur et leur aspect.', '', 'mise-en-forme-mise-en-page-et-impression.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(93, 'informatique13.webp', 'Les liens hypertextes', 'Les_liens_hypertextes', 'Un lien hypertexte est un objet multimédia (texte, image, son…) qui permet d’afficher d’autres informations\r\n(document, fichier…) lorsqu’on clique dessus.\r\n● Lorsqu’on fait passer la souris sur le lien hypertexte elle change de forme et prend la forme d’une main', 'Un lien hypertexte est un objet multimédia (texte, image, son…) qui permet d’afficher d’autres informations(document, fichier…) lorsqu’on clique dessus.\r\n Lorsqu’on fait passer la souris sur le lien hypertexte elle change de forme et prend la forme d’une main', 'Un lien hypertexte est un objet multimédia (texte, image, son…) qui permet d’afficher d’autres informations(document, fichier…) lorsqu’on clique dessus.\r\n Lorsqu’on fait passer la souris sur le lien hypertexte elle change de forme et prend la forme d’une main', '', 'les-liens-hypertextes.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(94, 'informatique14.webp', 'La recherche d’information sur un support de stockage', 'La_recherche_dinformation_sur_un_support_de_stockage', 'Définition : L’arborescence est la façon d’organisation des dossiers dans une unité de stockage.', 'Définition : L’arborescence est la façon d’organisation des dossiers dans une unité de stockage.', 'Définition : L’arborescence est la façon d’organisation des dossiers dans une unité de stockage.', '', 'la-recherche-d-information-sur-un-support-de-stockage.pdf', 'Computer Science,informatique,علوم الكمبيوتر', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(95, 'francais4.webp', ' Le verbe', 'Le_verbe', 'Le verbe est un élément central de la phrase, le verbe donne leur fonction aux mots, groupes de mots qui s’organisent autour de lui. Il permet d’apprécier, de situer dans le temps, les actions effectuées ou subies par les êtres et les choses. ', 'Le verbe est un élément central de la phrase, le verbe donne leur fonction aux mots, groupes de mots qui s’organisent autour de lui. Il permet d’apprécier, de situer dans le temps, les actions effectuées ou subies par les êtres et les choses. ', 'français', '', 'Le-verbe.docx', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 10, 75, '4'),
(96, 'francais7.webp', ' Le passé composé', 'Le_passé_composé', 'Le passé composé est un temps du passé qui indique des actions achevées, accomplies. Onl’utilise surtout à l’oral. Á l’écrit, on utilise plutôt le passé simple.', 'Le passé composé est un temps du passé qui indique des actions achevées, accomplies. Onl’utilise surtout à l’oral. Á l’écrit, on utilise plutôt le passé simple.', 'Le passé composé ', '', 'Le-passe-compose.pdf', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '4'),
(97, 'francais8.webp', ' Les temps du récit- l’imparfait et le passé simple', 'Les_temps_du_récit_limparfait_et_le_passé_simple', 'Pour raconter des événements et des faits passés, on utilise souvent\r\nl\'imparfait et le passé simple, appelés temps du récit.\r\n', 'Pour raconter des événements et des faits passés, on utilise souvent\r\nl\'imparfait et le passé simple, appelés temps du récit.\r\n', 'Pour raconter des événements et des faits passés, on utilise souvent\r\nl\'imparfait et le passé simple, appelés temps du récit.\r\n', '', 'Les-temps-du-recit-limparfait-et-le-passe-simple.pdf', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-09-09 23:00:00', 'all', 8, 75, '4'),
(98, 'francais9.webp', 'Les verbes transitifs et les verbes intransitifs', 'Les_verbes_transitifs_et_les_verbes_intransitifs', 'Les verbes transitifs et les verbes intransitifs', 'Les verbes transitifs et les verbes intransitifs', 'Les verbes transitifs et les verbes intransitifs', '', 'Les-verbes-transitifs-et-les-verbes-intransitifs.pdf', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '4'),
(99, 'francais5.webp', ' Le complément d’objet direct (COD) –', 'Le_complément_dobjet_direct_COD', ' Le complément d’objet direct (COD) ', ' Le complément d’objet direct  \r\n', ' Le complément d’objet direct \r\n', '', 'Le-complement-dobjet-direct-COD-Le-complement-dobjet-indirect-COI.pdf', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '4'),
(100, 'francais6.webp', ' Les verbes irréguliers', 'Les_verbes_irréguliers', ' Les verbes irréguliers\r\n\r\nfrançais', ' Les verbes irréguliers\r\n\r\n', ' Les verbes irréguliers\r\n\r\n', '', 'verbes-irregulieres.pdf', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '4'),
(103, 'francais10.webp', ' Les compléments circonstanciels', 'Les_compléments_circonstanciels', 'Un Complément Circonstanciel précise les circonstances dans lesquelles se déroule l’action exprimée par le verbe lieu de l\'action, durée, manière ..', 'Un Complément Circonstanciel précise les circonstances dans lesquelles se déroule l’action exprimée par le verbe lieu de l\'action, durée, manière ..', 'Un Complément Circonstanciel précise les circonstances dans lesquelles se déroule l’action exprimée par le verbe lieu de l\'action, durée, manière ..', '', 'Les-complements-circonstanciels.pdf', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '4'),
(104, 'francais11.webp', ' Les temps du passé (temps du récit)', 'Les_temps_du_passé_temps_du_récit', 'Les enfants sont en vacances. C’est samedi, je décide de les emmener à la plage. Je prépare les sandwichs, les boissons et les bouteilles d’eau. Je les range dans une glacière.', 'Les enfants sont en vacances. C’est samedi, je décide de les emmener à la plage. Je prépare les sandwichs, les boissons et les bouteilles d’eau. Je les range dans une glacière.', 'Les enfants sont en vacances. C’est samedi, je décide de les emmener à la plage. Je prépare les sandwichs, les boissons et les bouteilles d’eau. Je les range dans une glacière.', '', '', 'Apprendre le français, تعلم الفرنسية', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '4'),
(105, 'english2.webp', 'Oh, the Places You\'ll Go!', 'Oh_the_Places_Youll_Go', 'Explore the whimsical world of \'Oh, the Places You\'ll Go!\' by Dr. Seuss, a timeless tale of adventure and resilience for all ages', 'Explore the whimsical world of \'Oh, the Places You\'ll Go!\' by Dr. Seuss, a timeless tale of adventure and resilience for all ages', 'english', '', 'oh-the-places-youll-go-by-dr-seuss.pdf', 'Learn English, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(106, 'english3.webp', 'Wacky Wednesday', 'Wacky_Wednesday', '', 'Step into the wacky and wonderful world of \'Wacky Wednesday\' by Dr. Seuss, a delightful and imaginative picture book that celebrates the joy of silliness and unexpected surprises.', 'english', '', 'Wacky_Wednesday_-_Dr_Seuss.pdf', 'Learn English, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(107, 'english4.webp', 'On Beyond Zebra by Dr. Seuss.pdf', 'On_Beyond_Zebra_by_Dr_Seuss_pdf', 'Embark on a whimsical journey \'On Beyond Zebra\' by Dr. Seuss, a charming and imaginative book that invites readers to explore the world beyond the alphabet with delightful creatures and new, imaginary letters', 'Embark on a whimsical journey \'On Beyond Zebra\' by Dr. Seuss, a charming and imaginative book that invites readers to explore the world beyond the alphabet with delightful creatures and new, imaginary letters', 'Dr. Seuss, On Beyond Zebra by ', '', 'On Beyond Zebra by Dr. Seuss.pdf', 'Learn English, قصص و روايات, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(108, 'english5.webp', 'The Lorax', 'The_Lorax', 'Experience the environmental fable \'The Lorax\' by Dr. Seuss, a timeless and thought-provoking story that champions environmental conservation and the importance of protecting nature\'s beauty and resources', 'Experience the environmental fable \'The Lorax\' by Dr. Seuss, a timeless and thought-provoking story that champions environmental conservation and the importance of protecting nature\'s beauty and resources', 'Dr. Seuss;The Lorax', '', 'H3146_The Lorax_Storybook.pdf', 'Learn English, قصص و روايات, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(109, 'english6.webp', 'Dr.-Seuss-The-Cat-in-the-Hat-Random-House-1957.pdf', 'Dr_Seuss_The_Catin_the_Hat_Random_House_1957_pdf', 'Enter the whimsical world of \'The Cat in the Hat\' by Dr. Seuss, a timeless and playful tale that sparks the imagination and brings joy to readers of all ages', 'Enter the whimsical world of \'The Cat in the Hat\' by Dr. Seuss, a timeless and playful tale that sparks the imagination and brings joy to readers of all ages', 'The Cat in the Hat\'', '', 'Dr.-Seuss-The-Cat-in-the-Hat-Random-House-1957.pdf', 'Learn English, قصص و روايات, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(110, 'english7.webp', 'The Cat in the Hat Comes Back', 'The_Cat_in_the_Hat_Comes_Back', 'Dive into the delightful sequel \'The Cat in the Hat Comes Back\' by Dr. Seuss, a charming and mischievous story that continues the adventures of the beloved Cat in the Hat with playful rhymes and whimsical illustrations.', 'Dive into the delightful sequel \'The Cat in the Hat Comes Back\' by Dr. Seuss, a charming and mischievous story that continues the adventures of the beloved Cat in the Hat with playful rhymes and whimsical illustrations.', 'The Cat in the Hat Comes Back', '', 'books-library.online-01251716Ts9P9.pdf', 'Learn English, قصص و روايات, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(111, 'english8.webp', 'oobleck', 'oobleck', 'Experience the magical mischief of \'Bartholomew and the Oobleck\' by Dr. Seuss, a whimsical and enchanting tale that follows Bartholomew as he deals with the consequences of a king\'s unusual request for oobleck, a sticky green substance that causes chaos in the kingdom', 'Experience the magical mischief of \'Bartholomew and the Oobleck\' by Dr. Seuss, a whimsical and enchanting tale that follows Bartholomew as he deals with the consequences of a king\'s unusual request for oobleck, a sticky green substance that causes chaos in the kingdom', 'english', '', '1949_Bartholomew_And_The_Oobleck_Dr_Seuss.pdf', 'Learn English, قصص و روايات, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(112, 'english9.webp', 'Mr. Brown Can Moo! Can You? - Newton International School', 'Mr_Brown_Can_Moo_Can_You_Newton_International_School', 'Explore the world of sounds with Mr. Brown in this engaging children\'s book. The title, \"Mr. Brown Can Moo! Can You?\" invites young readers to join in the fun and discover the joy of interactive storytelling and imaginative play.\"', 'Explore the world of sounds with Mr. Brown in this engaging children\'s book. The title, \"Mr. Brown Can Moo! Can You?\" invites young readers to join in the fun and discover the joy of interactive storytelling and imaginative play.\"', 'english', '', 'Mr.-Brown-Can-Moo-Can-You-by-Dr.-Seuss-z-lib.org_.cbr_.pdf', 'Learn English, قصص و روايات, الانجليزية', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 8, 75, '0'),
(114, 'religion1.webp', 'The World\'s Religions', 'The_Worlds_Religions', '\"The World\'s Religions\" by Huston Smith is a comprehensive exploration of major religious traditions, offering insight into the beliefs, practices, and histories of Hinduism, Buddhism, Confucianism, Taoism, Islam, Judaism, and Christianity. Smith\'s engaging approach fosters interfaith understanding and invites readers to appreciate the beauty and complexity of diverse spiritual paths.', '\"The World\'s Religions\" by Huston Smith is a comprehensive exploration of major religious traditions, offering insight into the beliefs, practices, and histories of Hinduism, Buddhism, Confucianism, Taoism, Islam, Judaism, and Christianity. Smith\'s engaging approach fosters interfaith understanding and invites readers to appreciate the beauty and complexity of diverse spiritual paths.', 'The World\'s Religions', '', 'The-Worlds-Religions-Our-Great-Wisdom-Traditions-by-Huston-Smith-z-lib.org.pdf', 'أديان وفلسفات,فلسفة', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '10'),
(115, 'religion2.webp', '\"The Essential Rumi\" translated by Coleman Barks pdf', 'The_Essential_Rumi_translated_by_Coleman_Barks_pdf', '\"The Essential Rumi\" by Coleman Barks is a collection of Rumi\'s poetry translated into English. The book offers a selection of Rumi\'s most profound and inspiring poems, capturing the essence of Sufi mysticism and the universal themes of love, spirituality, and inner transformation. Barks\' translations beautifully convey the timeless wisdom and lyrical beauty of Rumi\'s poetry, making it accessible to a wide audience.', '\"The Essential Rumi\" by Coleman Barks is a collection of Rumi\'s poetry translated into English. The book offers a selection of Rumi\'s most profound and inspiring poems, capturing the essence of Sufi mysticism and the universal themes of love, spirituality, and inner transformation. Barks\' translations beautifully convey the timeless wisdom and lyrical beauty of Rumi\'s poetry, making it accessible to a wide audience.', '\"The Essential Rumi\" translated by Coleman Barks pdf', '', 'coleman-barks-the-essential-rumi.pdf', 'أديان وفلسفات,فلسفة', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '10');
INSERT INTO `books` (`books_id`, `Myimage`, `title`, `slug`, `Mysubject`, `Mydescription`, `keywords`, `Author`, `autre`, `the_type`, `dir`, `language`, `visibility_status`, `updated_at`, `created_at`, `gender`, `min_age`, `max_age`, `educational_level`) VALUES
(116, 'religion3.webp', '\"The Bhagavad Gita.\" translated by Eknath Easwaran pdf', 'The_Bhagavad_Gita_translated_by_Eknath_Easwaran_pdf', '\"The Bhagavad Gita\" translated by Eknath Easwaran presents a profound and accessible interpretation of the ancient Indian scripture. Easwaran\'s translation captures the timeless wisdom and spiritual insights of the Gita, offering readers a practical guide to life, self-realization, and the paths of devotion, action, and knowledge. The book provides valuable commentary and practical teachings that resonate with readers from diverse backgrounds, making it a cherished resource for spiritual seekers and scholars alike.', '\"The Bhagavad Gita\" translated by Eknath Easwaran presents a profound and accessible interpretation of the ancient Indian scripture. Easwaran\'s translation captures the timeless wisdom and spiritual insights of the Gita, offering readers a practical guide to life, self-realization, and the paths of devotion, action, and knowledge. The book provides valuable commentary and practical teachings that resonate with readers from diverse backgrounds, making it a cherished resource for spiritual seekers and scholars alike.', 'The Bhagavad Gita', '', 'The Bhagavad Gita.pdf', 'أديان وفلسفات,فلسفة', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 8, 75, '10'),
(117, 'religion4.webp', 'Muhammad Abdel Haleem | Understanding the Qur\'an', 'Muhammad_Abdel_Haleem_Understanding_the_Quran', '\"Understanding the Qur\'an\" by Muhammad Abdel Haleem offers a comprehensive and accessible guide to the teachings and wisdom of the Islamic holy book. Haleem\'s insightful commentary and clear explanations provide readers with a deeper understanding of the Qur\'an\'s profound spiritual and moral messages. The book serves as an invaluable resource for both Muslims and non-Muslims seeking to explore the timeless wisdom and ethical principles found within the Qur\'an.', '\"Understanding the Qur\'an\" by Muhammad Abdel Haleem offers a comprehensive and accessible guide to the teachings and wisdom of the Islamic holy book. Haleem\'s insightful commentary and clear explanations provide readers with a deeper understanding of the Qur\'an\'s profound spiritual and moral messages. The book serves as an invaluable resource for both Muslims and non-Muslims seeking to explore the timeless wisdom and ethical principles found within the Qur\'an.', 'Muslims+religion', '', 'Abdel-Haleem-Understanding-the-Quran.pdf', 'أديان وفلسفات,فلسفة', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 14, 75, '0'),
(119, 'religion7.webp', 'Book of Mormon', 'Book_of_Mormon', 'The \"Book of Mormon\" is a sacred text of the Latter-day Saint movement, which includes the Church of Jesus Christ of Latter-day Saints and other related denominations. It is regarded as a companion scripture to the Bible and is believed to contain an account of ancient prophets and their interactions with God in the Americas. The book recounts religious and historical narratives, including the ministry of Jesus Christ among the ancient inhabitants of the American continent. It is considered a foundational text for the faith and teachings of the Latter-day Saint tradition.', 'The \"Book of Mormon\" is a sacred text of the Latter-day Saint movement, which includes the Church of Jesus Christ of Latter-day Saints and other related denominations. It is regarded as a companion scripture to the Bible and is believed to contain an account of ancient prophets and their interactions with God in the Americas. The book recounts religious and historical narratives, including the ministry of Jesus Christ among the ancient inhabitants of the American continent. It is considered a foundational text for the faith and teachings of the Latter-day Saint tradition.', 'Book of Mormon', '', 'Book of Mormon.pdf', 'أديان وفلسفات,فلسفة', 'ltr', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 15, 75, '10'),
(120, 'Arabic1.webp', 'مزيد الثلاثي والرباعي ومعاني صيغ الزوائد', 'مزيد_الثلاثي_والرباعي_ومعاني_صيغ_الزوائد', 'يتضمن درس مزيد الثلاثي والرباعي ومعاني صيغ الزوائد للسنة الأولى اعدادي ما يلي', 'يتضمن درس مزيد الثلاثي والرباعي ومعاني صيغ الزوائد للسنة الأولى اعدادي ما يلي', 'يتضمن درس مزيد الثلاثي والرباعي ومعاني صيغ الزوائد للسنة الأولى اعدادي ما يلي', '', 'mzid-althlathi-oalrbaai-omaani-sigh-alzoaid.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(121, 'Arabic2.webp', 'تصريف الفعل الصحيح – السالم والمهموز والمضعف', 'تصريف_الفعل_الصحيح_السالم_والمهموز_والمضعف', 'تصريف الفعل الصحيح – السالم والمهموز والمضعف\r\n', 'تصريف الفعل الصحيح – السالم والمهموز والمضعف\r\n', 'تصريف الفعل الصحيح – السالم والمهموز والمضعف\r\n', '', 'tsrif-alfal-alshih-alsalm-oalmhmoz-oalmdhaf.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(122, 'Arabic3.webp', 'تصريف الفعل المعتل – المثال والأجوف', 'تصريف_الفعل_المعتل_المثال_والأجوف', ' درس تصريف الفعل المعتل المثال والأجوف للسنة الأولى اعدادي', ' درس تصريف الفعل المعتل المثال والأجوف للسنة الأولى اعدادي', ' درس تصريف الفعل المعتل المثال والأجوف للسنة الأولى اعدادي', '', 'tsrif-alfal-almatl-almthal-oalajof.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(123, 'Arabic4.webp', 'تصريف الفعل المعتل – الناقص', 'تصريف_الفعل_المعتل_الناقص', 'درس تصريف الفعل المعتل : الناقص للسنة الأولى اعدادي', 'درس تصريف الفعل المعتل : الناقص للسنة الأولى اعدادي', 'درس تصريف الفعل المعتل : الناقص للسنة الأولى اعدادي', '', 'tsrif-alfal-almatl-alnaqs.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(124, 'Arabic5.webp', 'تصريف الفعل اللفيف المفروق واللفيف المقرون', 'تصريف_الفعل_اللفيف_المفروق_واللفيف_المقرون', 'تصريف الفعل اللفيف المفروق واللفيف المقرون\r\n', 'تصريف الفعل اللفيف المفروق واللفيف المقرون\r\n', 'تصريف الفعل اللفيف المفروق واللفيف المقرون\r\n', '', 'tsrif-alfal-allfif-almfroq-oallfif-almqron.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(125, 'Arabic6.webp', 'الإعراب والبناء', 'الإعراب_والبناء', 'الإعراب والبناء', 'الإعراب والبناء', 'الإعراب والبناء', '', 'aliarab-oalbnaa-2.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(126, 'Arabic7.webp', 'الأسماء المعربة والأسماء المبنية', 'الأسماء_المعربة_والأسماء_المبنية', 'الأسماء المعربة والأسماء المبنية', 'الأسماء المعربة والأسماء المبنية\r\nتحديد الظاهرة اللغوية', 'الأسماء المعربة والأسماء المبنية', '', 'لأسماء-المعربة-والمبنية.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(127, 'Arabic8.webp', 'علامات البناء في الأفعال', 'علامات_البناء_في_الأفعال', 'علامات البناء في الأفعال', 'علامات البناء في الأفعال\r\nI تحديد الظاهرة اللغوية وملاحظتها ', 'علامات البناء في الأفعال\r\n', '', 'علامات-البناء-في-الأفعال.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 2, 75, '4'),
(128, 'Arabic9.webp', 'إعراب الفعل المضارع – رفعه ونصبه', 'إعراب_الفعل_المضارع_رفعه_ونصبه', 'إعراب الفعل المضارع – رفعه ونصبه', 'إعراب الفعل المضارع – رفعه ونصبه', 'إعراب الفعل المضارع – رفعه ونصبه', '', 'إعراب-الفعل-المضارع-رفعه-ونصبه.doc', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(129, 'Arabic10.webp', 'إعراب الفعل المضارع – جزمه', 'إعراب_الفعل_المضارع__جزمه', 'إعراب الفعل المضارع – جزمه', 'إعراب الفعل المضارع – جزمه', 'إعراب الفعل المضارع – جزمه', '', 'إعراب-الفعل-المضارع-جزمه.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(130, 'Arabic11.webp', 'مهارة توسيع فكرة وتفسيرها', 'مهارة_توسيع_فكرة_وتفسيرها', 'مهارة توسيع فكرة وتفسيرها', 'مهارة توسيع فكرة وتفسيرها\r\n مهارة توسيع فكرة توليد أفكار جديدة ', 'مهارة توسيع فكرة وتفسيرها', '', 'درس-مهارة-توسيع-فكرة-وتفسيرها.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(131, 'Arabic12.webp', 'مهارة تعريف الكتاب وإعداد بطاقة لتقديمه', 'مهارة_تعريف_الكتاب_وإعداد_بطاقة_لتقديمه', 'مهارة تعريف الكتاب وإعداد بطاقة لتقديمه', 'مهارة تعريف الكتاب وإعداد بطاقة لتقديمه', 'مهارة تعريف الكتاب وإعداد بطاقة لتقديمه', '', 'مهارة-تعريف-الكتاب-وإعداد-بطاقة-لتقديمه.pdf', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(132, 'Arabic13.webp', 'مهارة البحث عن المعلومات وإعداد ملفات وثائقية', 'مهارة_البحث_عن_المعلومات_وإعداد_ملفات_وثائقية', 'مهارة البحث عن المعلومات وإعداد ملفات وثائقية\r\n', 'مهارة البحث عن المعلومات وإعداد ملفات وثائقية\r\n', 'مهارة البحث عن المعلومات وإعداد ملفات وثائقية\r\n', '', 'درس-مهارة-البحث-عن-المعلومات-وإعداد-ملفات-وثائقية.doc', 'كتب باللغة العربية', 'rtl', '', 'public', '2025-09-08 23:11:17', '2024-08-20 23:00:00', 'all', 11, 75, '4'),
(133, 'humain_rights.webp', 'Déclaration universelle des droits de l\'homme  pdf', 'Déclaration_universelle_des_droits_de_lhomme_pdf', 'La Déclaration universelle des droits de l\'homme est un document adopté par l\'Assemblée générale des Nations Unies en 1948. Elle énonce les droits fondamentaux de tous les êtres humains, tels que le droit à la vie, à la liberté, à la sécurité, à l\'égalité, à un procès équitable, à la liberté d\'expression et à l\'éducation. La Déclaration vise à promouvoir la dignité humaine, la justice et la paix dans le monde.', 'La Déclaration universelle des droits de l\'homme est un document adopté par l\'Assemblée générale des Nations Unies en 1948. Elle énonce les droits fondamentaux de tous les êtres humains, tels que le droit à la vie, à la liberté, à la sécurité, à l\'égalité, à un procès équitable, à la liberté d\'expression et à l\'éducation. La Déclaration vise à promouvoir la dignité humaine, la justice et la paix dans le monde.', 'Déclaration universelle des droits de l\'homme', '', 'humain_rights.pdf', 'القانون وحقوق الإنسان', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(134, 'kids_rights.webp', 'Les droits de l’enfant pdf', 'Les_droits_de_lenfant_pdf', 'Les droits de l\'enfant\" est un livre qui aborde les droits fondamentaux des enfants, tels que le droit à l\'éducation, à la santé, à la protection et à la participation. Ce livre met en lumière l\'importance de garantir le bien-être des enfants et de les protéger contre la violence, l\'exploitation et la négligence. Il souligne également le rôle crucial des adultes et de la société dans la promotion et la protection des droits des enfants. Ce sujet est d\'une grande importance car il met en avant les besoins spécifiques des enfants et souligne l\'importance de veiller à leur bien-être et à leur épanouissement.', 'Les droits de l\'enfant\" est un livre qui aborde les droits fondamentaux des enfants, tels que le droit à l\'éducation, à la santé, à la protection et à la participation. Ce livre met en lumière l\'importance de garantir le bien-être des enfants et de les protéger contre la violence, l\'exploitation et la négligence. Il souligne également le rôle crucial des adultes et de la société dans la promotion et la protection des droits des enfants. ', 'Les droits de l\'enfant', '', 'kids_rights.pdf', 'القانون وحقوق الإنسان', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(135, 'wommens_rights_mans_rights.webp', 'Les droits des femmes sont des droits de l’Homme pdff', 'Les_droits_des_femmes_sont_des_droits_de_lHomme_pdff', '\"Les droits des femmes sont des droits de l’Homme\" est un livre qui défend l\'idée que les droits des femmes sont des droits humains. Il aborde les luttes pour l\'égalité des sexes et met en lumière l\'importance de garantir l\'égalité des droits pour tous.', '\"Les droits des femmes sont des droits de l’Homme\" est un livre qui défend l\'idée que les droits des femmes sont des droits humains. Il aborde les luttes pour l\'égalité des sexes et met en lumière l\'importance de garantir l\'égalité des droits pour tous.', 'Les droits des femmes sont des droits de l’Homme', '', 'wommens_rights_mans_rights.pdf', 'القانون وحقوق الإنسان', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(136, 'Le_Droit_des_Femmes.webp', 'Déclaration Universelle des Droits de la Femme pdf', 'Déclaration_Universelle_des_Droits_de_la_Femme_pdf', 'Les droits des femmes sont des droits revendiqués pour les femmes dans de nombreuses sociétés à travers le monde, qui constituent la base du mouvement pour les droits des femmes du xixe siècle ainsi que le combat des mouvements féministes depuis le xxe siècle. ', 'Les droits des femmes sont des droits revendiqués pour les femmes dans de nombreuses sociétés à travers le monde, qui constituent la base du mouvement pour les droits des femmes du xixe siècle ainsi que le combat des mouvements féministes depuis le xxe siècle. ', 'Les droits des femmes', '', 'Declaration-universelle-des-droits-de-la-femme.pdf', 'القانون وحقوق الإنسان', 'ltr', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 2, 75, '0'),
(137, 'code_de_famille.webp', 'مدونة الأسرة pdf', 'مدونة_الأسرة_pdf', 'مدوَّنة الأُسرة المغربية أو المدوّنة هي قانون وضعه برلمان المغرب سنة 2004 وأقرّه الملك محمد السادس، هو القاعدة المحدِّدة للشروط والواجبات والحقوق في حالات عائلية كالخطبة، والنكاح، والطلاق وكذا الحضانة والنَفَقَة والوَصاة.', 'مدوَّنة الأُسرة المغربية أو المدوّنة هي قانون وضعه برلمان المغرب سنة 2004 وأقرّه الملك محمد السادس، هو القاعدة المحدِّدة للشروط والواجبات والحقوق في حالات عائلية كالخطبة، والنكاح، والطلاق وكذا الحضانة والنَفَقَة والوَصاة.', 'مدونة الأسرة', '', 'مدونة الأسرة 2016.pdf', 'القانون وحقوق الإنسان', 'rtl', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(138, 'Constitutions_marocaines.webp', 'الدستور المغربي 2011 pdf', 'الدستور_المغربي_2011_pdf', 'دستور المغرب هو القانون الأسمى والسند الذي تنبثق منه باقي القوانين. تطور الدستور على مدى 100 سنة، فأول دستور للبلاد كان عام 1908 وآخر دستور هو دستور سنة 2011 الدي ضل العمل به ساريا إلى يومنا هدا.', 'دستور المغرب هو القانون الأسمى والسند الذي تنبثق منه باقي القوانين. تطور الدستور على مدى 100 سنة، فأول دستور للبلاد كان عام 1908 وآخر دستور هو دستور سنة 2011 الدي ضل العمل به ساريا إلى يومنا هدا.', 'دستور المغرب', '', 'الدستور.pdf', 'القانون وحقوق الإنسان', 'rtl', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(139, 'القانون_الجنائي.webp', 'القانون الجنائي المغربي pdf', 'القانون_الجنائي_المغربي_pdf', 'القانون الجنائي قانون ينظم كيفية معاقبة كل من خالف قاعدة قانونية وفرض العقوبة القانونية عليه وتحديد الافعال المباحة والمحرمة ويوجب لكل جريمة جزاء.<br>\r\nرابط قراءة كتاب :\r\n<a target=\"_blank\" href=\"LawsView.php?the_type=القانون+الجنائي&filter=اختيار+\">القانون الجنائي المغربي</a>', 'القانون الجنائي قانون ينظم كيفية معاقبة كل من خالف قاعدة قانونية وفرض العقوبة القانونية عليه وتحديد الافعال المباحة والمحرمة ويوجب لكل جريمة جزاء.', 'القانون الجنائي', '', 'مجموعة القانون الجنائي.pdf', 'القانون وحقوق الإنسان', 'rtl', 'Ar', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(140, 'مدونة_الالتزامات_والعقود.webp', 'مدونة الالتزامات والعقود pdf', 'مدونة_الالتزامات_والعقود_pdf', 'قانون الالتزامات والعقود هو تدوين لقانون العقود في المغرب، بناء على ظهير 9 رمضان 1331 (الصادر في 12 أغسطس 1913) في عهد مولاي يوسف، خلال الحماية الفرنسية على المغرب بصيغتها المعدلة والمستكملة من 1917 إلى 2016.', 'قانون الالتزامات والعقود هو تدوين لقانون العقود في المغرب، بناء على ظهير 9 رمضان 1331 (الصادر في 12 أغسطس 1913) في عهد مولاي يوسف، خلال الحماية الفرنسية على المغرب بصيغتها المعدلة والمستكملة من 1917 إلى 2016.', 'قانون الالتزامات والعقود', '', 'مدونة_الالتزامات_والعقود.pdf', 'القانون وحقوق الإنسان', 'rtl', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 14, 75, '0'),
(141, 'kaiss_ibn_malouh.webp', 'دوان مجنون ليلى .. قيس ابن الملوح', 'دوان_مجنون_ليلى_قيس_ابن_الملوح', 'قيس ابن الملوح أو مجنون ليلى من أشهر شعراء الغزل وهو الذي حدثت معه قصة غرامية طويلة من أشهر قصص الغرام في التاريخ وهذا ديوان يحتوي على شعر قيس بن الملوح ...', 'قيس ابن الملوح أو مجنون ليلى من أشهر شعراء الغزل وهو الذي حدثت معه قصة غرامية طويلة من أشهر قصص الغرام في التاريخ وهذا ديوان يحتوي على شعر قيس بن الملوح ...', 'مجنون ليلى', '', 'kaiss_ibn_malouh.pdf', 'قصائد شعرية', 'rtl', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(142, 'chafiai.webp', 'ديوان الشافعي pdf', 'ديوان_الشافعي_pdf', 'دوان الإمام الشافعي هو ملابس داخلية رجالية تتكون من قطعتين، الأولى تغطي الخصر والفخذين، والثانية تغطي الفخذين وتنزل إلى الركبتين. تعتبر دوان الإمام الشافعي جزءًا من الزي التقليدي في بعض المجتمعات الشرقية، ويُرتديها الرجال تحت الثوب أو الجلباب.\r\n', 'دوان الإمام الشافعي هو ملابس داخلية رجالية تتكون من قطعتين، الأولى تغطي الخصر والفخذين، والثانية تغطي الفخذين وتنزل إلى الركبتين. تعتبر دوان الإمام الشافعي جزءًا من الزي التقليدي في بعض المجتمعات الشرقية، ويُرتديها الرجال تحت الثوب أو الجلباب.\r\n', 'دوان الإمام الشافعي', '', 'ديوان الشافعي.pdf', 'قصائد شعرية', 'rtl', '', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(143, 'code_de_travail.webp', 'قانون الشغل المغربي PDF', 'قانون_الشغل_المغربي_PDF', 'تسري أحكام هذا القانون على األشخاص المرتبطين بعقد شغل، أيا كانت طرق تنفيذه ، وطبيعة. األجر المقرر فيه، وكيفية أدائه ، وأيا كان نوع المقاولة التي ينفذ العقد ...\r\n<br>\r\nرابط قراءة كتاب :\r\n<a target=\"_blank\" href=\"LawsView.php?the_type=مدونة+الشغل&filter=اختيار+\">قانون الشغل</a>', 'تسري أحكام هذا القانون على األشخاص المرتبطين بعقد شغل، أيا كانت طرق تنفيذه ، وطبيعة. األجر المقرر فيه، وكيفية أدائه ، وأيا كان نوع المقاولة التي ينفذ العقد ...', 'قانون الشغل', 'مجلة تيفيناغ', 'code_travail.pdf', 'القانون وحقوق الإنسان', 'rtl', 'Ar', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 11, 75, '0'),
(144, 'code_de_travail_2.webp', 'حوادث الشغل والأمراض المهنية.pdf', 'حوادث_الشغل_والأمراض_المهنية_pdf', 'كتاب &quot;قانون حوادث الشغل والأمراض المهنية&quot; يتناول القوانين والتشريعات المتعلقة بحوادث الشغل (العمل) والأمراض المهنية في سياق العمل.<br>\r\nرابط قراءة الكتاب :\r\n<a target=\"_blank\" href=\"LawsView.php?the_type=قانون+التعويض+عن+حوادث+الشغل&filter=اختيار+\">قانون التعويض عن حوادث الشغل\r\n</a>', 'كتاب قانون حوادث الشغل والأمراض المهنية يتناول القوانين والتشريعات المتعلقة بحوادث الشغل (العمل) والأمراض المهنية في سياق العمل.', 'كتاب قانون حوادث الشغل والأمراض المهنية, التشريعات المتعلقة بحوادث الشغل, العمل', '', 'حوادث الشغل والأمراض المهنية.pdf', 'القانون وحقوق الإنسان', 'rtl', 'Ar', 'public', '2025-09-08 23:08:14', '2024-08-20 23:00:00', 'all', 14, 75, '0'),
(145, 'seance_1_limites_et_derivation__rappel_1_image.webp', 'séance 1: limites et dérivation - rappel 1', 'seance_1_limites_et_derivation_rappel_1', NULL, NULL, NULL, 'موقع تيفيناغ', 'seance_1_limites_et_derivation__rappel_1_file.pdf', 'رياضيات', 'ltr', NULL, 'public', '2025-09-08 23:11:17', '2025-04-06 17:53:34', 'all', 2, 75, '9'),
(146, 'seance_2__continuite_partie_17_image.webp', 'séance 2 : continuité partie 1/7', 'seance_2_continuite_partie_1_7', NULL, NULL, NULL, 'موقع تيفيناغ', 'seance_2__continuite_partie_17_file.pdf', 'رياضيات', 'ltr', NULL, 'public', '2025-09-08 23:11:17', '2025-04-06 18:14:07', 'all', 2, 75, '9'),
(147, 'seance_3_continuite__partie_22_image.webp', 'séance 3: continuité - partie 2/2', 'seance_3_continuite_partie_2_2', NULL, NULL, NULL, 'موقع تيفيناغ', 'seance_3_continuite__partie_22_file.pdf', 'رياضيات', 'ltr', NULL, 'public', '2025-09-08 23:11:17', '2025-04-06 18:38:25', 'all', 2, 75, '9');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`books_id`),
  ADD UNIQUE KEY `slug` (`slug`),
  ADD UNIQUE KEY `title` (`title`) USING HASH,
  ADD UNIQUE KEY `subject` (`Mysubject`) USING HASH;

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `books`
--
ALTER TABLE `books`
  MODIFY `books_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=165;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
